name: "NixOS"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: sakulk-nixos
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.saku-nixos.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.saku-thinkpad.config.system.build.toplevel
