name: "NixOS"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Remove unnecessary packages
      run: |
        echo "=== Before pruning ==="
        df -h
        sudo rm -rf /usr/share /usr/local /opt || true
        echo "=== After pruning ==="
        df -h
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: sakulk-nixos
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.saku-nixos.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.saku-thinkpad.config.system.build.toplevel
